config/routes.rb
Excorpse::Application.routes.draw do
  root :to => "home#index"

  devise_for :users

  resources :games do
    collection do
      get :continue
    end
    resources :steps, :except => [ :edit, :update ]
  end

end

app/models/game.rb
require 'RMagick'

class Game < ActiveRecord::Base
  attr_accessible :complete

  has_attached_file :image, styles: {thumb: "260x"}
  has_many :steps
  has_many :users, :through => :steps

  def create_image
    image_list = []
    self.steps.each { |step| image_list << step.image.path }
    complete_image = Magick::ImageList.new(*image_list).append true

    file = Tempfile.new('complete_image.png')
    complete_image.write(file.path)

    self.image = file
    return self.save
  end
end

app/models/step.rb
class Step < ActiveRecord::Base
  attr_accessor :image_data
  attr_accessible :contents, :sequence_id, :game_id, :user_id, :image, :image_data
  has_attached_file :image,
    :styles => { :preview => '' },
    :convert_options => { :preview => '-crop 725x25+0+325' }

  belongs_to :game
  belongs_to :user

  def save_image(image_data)
    image_data = image_data.split(',').pop
    self.image = Paperclip::string_to_file('image.png', 'img/png', image_data)
    return self.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :steps
  has_many :games, :through => :steps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :authenticate_user!

  # GET /games
  # GET /games.json
  def index
    @games = Game.where(:complete => true).all

    respond_to do |format|
      format.html # index.html.erb
      # format.json { render json: @games }
    end
  end

  def continue
    @game = User.where('id != ?', current_user.id).all.games.where(:complete => 0).first

    if @game
      redirect_to new_game_step_path(@game)
    else
      redirect_to home, notice: "Sorry, you've participated in all of the current games. You should start a new one instead!"
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])

    if @game.complete
      @game.create_image unless @game.image?

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @game }
      end
    else
      redirect_to new_game_step_path(@game)
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new
    @game.save
    redirect_to new_game_step_path(@game)
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:Game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @newest_games = Game.order('created_at DESC').where(:complete => 1).limit(5).all
    @users_games = current_user.games.order('created_at DESC').where(:complete => 1).uniq.limit(5).all
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_filter :authenticate_user!

  # GET games/1/steps
  # GET games/1/steps.json
  def index
    find_game
    redirect_to game_url(@game)
  end

  # GET games/1/steps/1
  # GET games/1/steps/1.json
  def show
    find_game
    @step = Step.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @step }
    end
  end

  # GET games/1/steps/new
  # GET games/1/steps/new.json
  def new
    find_game
    @step = @game.steps.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @step }
    end
  end

  # POST games/1/steps
  # POST games/1/steps.json
  def create
    find_game
    @step = @game.steps.build(params[:step])
    @step.user = current_user
    @step.game_index = @game.steps.count + 1
    @step.save_image(params[:step][:image_data])

    respond_to do |format|
      if @step.save
        @game.complete = true if @game.steps.count >= 3
        @game.save

        if @game.complete
          format.html { redirect_to game_url(@game), notice: "You finished this exquisite corpse! Here's the final product." }
        else
          format.html { redirect_to home, notice: "Nice one! We'll let you know when the game is finished and the final drawing is ready." }
        end
        format.json { render json: @step, status: :created, location: @step }
      else
        format.html { render action: "new" }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE games/1/steps/1
  # DELETE games/1/steps/1.json
  def destroy
    @step = Step.find(params[:id])
    @step.destroy

    respond_to do |format|
      format.html { redirect_to game_steps_url }
      format.json { head :no_content }
    end
  end

  protected
    def find_game
      @game = Game.find(params[:game_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sequences_helper.rb
module SequencesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this sequence from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing sequence</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Games</h1>
<h2>Finished Games</h2>
<%= render "shared/game_list" %>

<%= link_to 'New Game', new_game_path, :class => 'btn' %>

app/views/games/new.html.erb
<h1>New sequence</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<h1>Game #<%= @game.id %></h1>
<h2>Made by <%= @game.users.pluck(:email).to_sentence %></h2>

<%= image_tag @game.image %>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/home/index.html.erb
<h1>Welcome to ExCorpse</h1>

<hr>

<div style="text-align: center">
  <%= link_to 'Start a New Game', new_game_path, class: 'btn btn-primary btn-large' %>
  <%= link_to 'Continue a Game', continue_games_path, class: 'btn btn-primary btn-large' %>
</div>

<hr>

<h2>Latest Games</h2>
<%= render partial: "shared/game_list", locals: { games: @newest_games } %>

<hr>

<h2>Your Completed Games</h2>
<%= render partial: "shared/game_list", locals: { games: @users_games } %>
<% @newest_games.each do |game| %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Excorpse</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= yield :head %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>

   <header class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container-fluid">
        <%= link_to "excorpse", root_path, class: "brand" %>
        <nav>
          <ul class="nav pull-right">
            <li><%= link_to "Home", root_path %></li>
            <% if user_signed_in? %>
            <li><%= link_to "Play", games_path %></li>
            <li>
            <%= link_to('Your Account', edit_user_registration_path) %>
            </li>
            <li>
            <%= link_to('Log Out', destroy_user_session_path, :method => :delete) %>
            </li>
            <% else %>
            <li>
            <%= link_to('Log In', new_user_session_path)  %>
            </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </header>

  <div class="container-fluid">
    <% if notice %><div class="alert"><%= notice %></div><% end %>
    <% if alert %><div class="alert alert-error"><%= alert %></div><% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/shared/_doodler.html.erb
<div class="canvas-container"><canvas id="canvas"></canvas></div>

<ul class="colors option">
  <li data-color="black" class="selected"></li>
  <li data-color="white"></li>
  <li data-color="red"></li>
  <li data-color="orange"></li>
  <li data-color="yellow"></li>
  <li data-color="blue"></li>
  <li data-color="green"></li>
  <li data-color="indigo"></li>
  <li data-color="violet"></li>
</ul>

<ul class="sizes option">
  <li data-size="1" class="selected"></li>
  <li data-size="5"></li>
  <li data-size="10"></li>
  <li data-size="15"></li>
  <li data-size="20"></li>
  <li data-size="35"></li>
  <li data-size="50"></li>
</ul>

app/views/shared/_game_list.erb
<ul class="thumbnails">
<% games.each do |game| %>
  <li class="span3">
    <div class="thumbnail">
      <%= link_to image_tag(game.image :thumb), game %>
    </div>
  </li>
<% end %>
</ul>

app/views/steps/_doodler.html.erb
<div class="canvas-container<%= ' first' if @game.steps.count == 0 %>">
  <% if @game.steps.count > 0 %>
  <%= image_tag @game.steps.order(:game_index).last.image(:preview), alt: '', class: 'preview' %>
  <% end %>
  <canvas id="canvas"></canvas>
</div>

<ul class="colors option">
  <li data-color="black" class="selected"></li>
  <li data-color="white"></li>
  <li data-color="red"></li>
  <li data-color="orange"></li>
  <li data-color="yellow"></li>
  <li data-color="blue"></li>
  <li data-color="green"></li>
  <li data-color="indigo"></li>
  <li data-color="violet"></li>
</ul>

<ul class="sizes option">
  <li data-size="1" class="selected"></li>
  <li data-size="5"></li>
  <li data-size="10"></li>
  <li data-size="15"></li>
  <li data-size="20"></li>
  <li data-size="35"></li>
  <li data-size="50"></li>
</ul>

app/views/steps/edit.html.erb
<h1>Editing step</h1>

<%= render 'form' %>

<%= link_to 'Show', @step %> |
<%= link_to 'Back', sequence_steps_path %>

app/views/steps/index.html.erb
<h1>Listing steps</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @steps.each do |step| %>
  <tr>
    <td><%= link_to 'Show', game_step_path(@game, step) %></td>
    <td><%= link_to 'Edit', edit_game_step_path(@game, step) %></td>
    <td><%= link_to 'Destroy', game_step_path(@game, step), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Step', new_game_step_path(@game) %>

app/views/steps/new.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    var canvas;
    $(function() {
      canvas = new Canvas({ id: 'canvas', width: 725, height: 350 });

      $('#clear').on('click', function() { canvas.clear(); });

      $('.colors li').css('backgroundColor', function() {
        return $(this).data('color');
      }).on('click', function() {
        canvas.setStrokeColor($(this).data('color'));
        $(this).addClass('selected').siblings().removeClass('selected');
      });

      $('.sizes li').each(function() {
        var size = $(this).data('size');
        $('<div class="circle"></div>').css({
          width: size,
          height: size
        }).appendTo($(this));
      }).on('click', function() {
        canvas.setStrokeWidth($(this).data('size'));
        $(this).addClass('selected').siblings().removeClass('selected');
      });

      $(window).on('mouseup', function() {
        $('#step_contents').val(JSON.stringify(canvas.recording.toJSON()));
        $('#step_image_data').val(canvas.el.toDataURL());
      });
    });
  </script>
<% end %>

<h1>Draw!</h1>

<%= form_for([@game, @step]) do |f| %>

  <%= render "doodler" %>

  <%= f.hidden_field :contents %>
  <%= f.hidden_field :image_data %>

  <div class="actions">
    <a href="#" id="clear" class="btn">Start Over</a>
    <%= f.submit "I'm done!", class: 'btn btn-large' %>
  </div>
<% end %>

app/views/steps/show.html.erb
<%= image_tag @step.image %>

<p>Drawn by <%= @step.user.email %></p>

<%= link_to 'Back', game_path(@game) %>